// <auto-generated />
using System;
using Koala.Yedpa.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Koala.Yedpa.Repositories.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251224093742_005")]
    partial class _005
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Koala.Yedpa.Core.Models.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("StatusEnum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.BudgetRatio", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BuggetRatioMounths")
                        .HasColumnType("int");

                    b.Property<int>("BuggetType")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Ratio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalBugget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuggetType");

                    b.HasIndex("Year");

                    b.HasIndex("Code", "Year")
                        .IsUnique();

                    b.ToTable("BudgetRatio");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Claims", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.DuesStatistic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("April")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("August")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BudgetType")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<string>("BuggetRatioId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ClientRef")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("December")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DivCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DivName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("DocTrackingNr")
                        .HasColumnType("bigint");

                    b.Property<decimal>("February")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("January")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("July")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("June")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("March")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("May")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("November")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("October")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("September")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransferStatus")
                        .HasColumnType("int");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("DuesStatistics", "dbo");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.EmailTemplate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplate");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.ExtendedProperties", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InputType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShowOn")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("ExtendedProperties");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.ExtendedPropertyRecordValues", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExtendedPropertyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RecordId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExtendedPropertyId");

                    b.ToTable("ExtendedPropertyRecordValues");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.ExtendedPropertyValues", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtendedPropertyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExtendedPropertyId");

                    b.ToTable("ExtendedPropertyValues");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.GeneratedIds", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Digit")
                        .HasColumnType("int");

                    b.Property<int>("LastNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartNumber")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("GeneratedIds");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.LgXt001211", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int?>("Active")
                        .HasColumnType("int")
                        .HasColumnName("ACTIVE");

                    b.Property<DateTime?>("ActiveResDate")
                        .HasColumnType("datetime")
                        .HasColumnName("ACTIVERESDATE");

                    b.Property<DateTime?>("BegDate")
                        .HasColumnType("datetime")
                        .HasColumnName("BEGDATE");

                    b.Property<int?>("BlockRef")
                        .HasColumnType("int")
                        .HasColumnName("BLOCKREF");

                    b.Property<double?>("BudgetDepotCoefficient1")
                        .HasColumnType("float")
                        .HasColumnName("BUDGETDEPOTCOEFFICIENT1");

                    b.Property<double?>("BudgetDepotCoefficient2")
                        .HasColumnType("float")
                        .HasColumnName("BUDGETDEPOTCOEFFICIENT2");

                    b.Property<double?>("BudgetDepotMetre1")
                        .HasColumnType("float")
                        .HasColumnName("BUDGETDEPOTMETRE1");

                    b.Property<double?>("BudgetDepotMetre2")
                        .HasColumnType("float")
                        .HasColumnName("BUDGETDEPOTMETRE2");

                    b.Property<double?>("BudgetFloorCoefficient")
                        .HasColumnType("float")
                        .HasColumnName("BUDGETFLOORCOEFFICIENT");

                    b.Property<double?>("BudgetFloorMetre")
                        .HasColumnType("float")
                        .HasColumnName("BUDGETFLOORMETRE");

                    b.Property<double?>("BudgetGroundCoefficient")
                        .HasColumnType("float")
                        .HasColumnName("BUDGETGROUNDCOEFFICIENT");

                    b.Property<double?>("BudgetGroundMetre")
                        .HasColumnType("float")
                        .HasColumnName("BUDGETGROUNDMETRE");

                    b.Property<double?>("BudgetHungCoefficient")
                        .HasColumnType("float")
                        .HasColumnName("BUDGETHUNGCOEFFICIENT");

                    b.Property<double?>("BudgetHungMetre")
                        .HasColumnType("float")
                        .HasColumnName("BUDGETHUNGMETRE");

                    b.Property<double?>("BudgetPassageCoefficient1")
                        .HasColumnType("float")
                        .HasColumnName("BUDGETPASSAGECOEFFICIENT1");

                    b.Property<double?>("BudgetPassageCoefficient2")
                        .HasColumnType("float")
                        .HasColumnName("BUDGETPASSAGECOEFFICIENT2");

                    b.Property<double?>("BudgetPassageMetre1")
                        .HasColumnType("float")
                        .HasColumnName("BUDGETPASSAGEMETRE1");

                    b.Property<double?>("BudgetPassageMetre2")
                        .HasColumnType("float")
                        .HasColumnName("BUDGETPASSAGEMETRE2");

                    b.Property<string>("CalMeterNo")
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)")
                        .HasColumnName("CALMETERNO");

                    b.Property<int?>("CauldronRef")
                        .HasColumnType("int")
                        .HasColumnName("CAULDRONREF");

                    b.Property<short?>("ChiefReg")
                        .HasColumnType("smallint")
                        .HasColumnName("CHIEFREG");

                    b.Property<string>("ClientCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CLIENTCODE");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CLIENTNAME");

                    b.Property<short?>("CustomerType")
                        .HasColumnType("smallint")
                        .HasColumnName("CUSTOMER_TYPE");

                    b.Property<short?>("DeedInfo")
                        .HasColumnType("smallint")
                        .HasColumnName("DEEDINFO");

                    b.Property<double?>("DimField")
                        .HasColumnType("float")
                        .HasColumnName("DIMFIELD");

                    b.Property<double?>("DimGross")
                        .HasColumnType("float")
                        .HasColumnName("DIMGROSS");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("ENDDATE");

                    b.Property<double?>("FuelDepotCoefficient1")
                        .HasColumnType("float")
                        .HasColumnName("FUELDEPOTCOEFFICIENT1");

                    b.Property<double?>("FuelDepotCoefficient2")
                        .HasColumnType("float")
                        .HasColumnName("FUELDEPOTCOEFFICIENT2");

                    b.Property<double?>("FuelDepotMetre1")
                        .HasColumnType("float")
                        .HasColumnName("FUELDEPOTMETRE1");

                    b.Property<double?>("FuelDepotMetre2")
                        .HasColumnType("float")
                        .HasColumnName("FUELDEPOTMETRE2");

                    b.Property<double?>("FuelFloorCoefficient")
                        .HasColumnType("float")
                        .HasColumnName("FUELFLOORCOEFFICIENT");

                    b.Property<double?>("FuelFloorMetre")
                        .HasColumnType("float")
                        .HasColumnName("FUELFLOORMETRE");

                    b.Property<double?>("FuelGroundCoefficient")
                        .HasColumnType("float")
                        .HasColumnName("FUELGROUNDCOEFFICIENT");

                    b.Property<double?>("FuelGroundMetre")
                        .HasColumnType("float")
                        .HasColumnName("FUELGROUNDMETRE");

                    b.Property<double?>("FuelHungCoefficient")
                        .HasColumnType("float")
                        .HasColumnName("FUELHUNGCOEFFICIENT");

                    b.Property<double?>("FuelHungMetre")
                        .HasColumnType("float")
                        .HasColumnName("FUELHUNGMETRE");

                    b.Property<double?>("FuelPassageCoefficient1")
                        .HasColumnType("float")
                        .HasColumnName("FUELPASSAGECOEFFICIENT1");

                    b.Property<double?>("FuelPassageCoefficient2")
                        .HasColumnType("float")
                        .HasColumnName("FUELPASSAGECOEFFICIENT2");

                    b.Property<double?>("FuelPassageMetre1")
                        .HasColumnType("float")
                        .HasColumnName("FUELPASSAGEMETRE1");

                    b.Property<double?>("FuelPassageMetre2")
                        .HasColumnType("float")
                        .HasColumnName("FUELPASSAGEMETRE2");

                    b.Property<double?>("GasCoefficient")
                        .HasColumnType("float")
                        .HasColumnName("GASCOEFFICIENT");

                    b.Property<string>("GroupCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GROUPCODE");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GROUPNAME");

                    b.Property<string>("HotWaterMeterNo")
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)")
                        .HasColumnName("HOTWATERMETERNO");

                    b.Property<string>("IdentityNr")
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)")
                        .HasColumnName("IDENTITYNR");

                    b.Property<string>("IndDivNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("INDDIVNO");

                    b.Property<int>("LogRef")
                        .HasColumnType("int")
                        .HasColumnName("LOGREF");

                    b.Property<DateTime?>("OfficialBegDate")
                        .HasColumnType("datetime")
                        .HasColumnName("OFFICIALBEGDATE");

                    b.Property<DateTime?>("OfficialEndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("OFFICIALENDDATE");

                    b.Property<int?>("ParLogRef")
                        .HasColumnType("int")
                        .HasColumnName("PARLOGREF");

                    b.Property<int?>("ParcelRef")
                        .HasColumnType("int")
                        .HasColumnName("PARCELREF");

                    b.Property<int?>("ParentClRef")
                        .HasColumnType("int")
                        .HasColumnName("PARENTCLREF");

                    b.Property<short?>("PersonCount")
                        .HasColumnType("smallint")
                        .HasColumnName("PERSONCOUNT");

                    b.Property<int?>("PhaseRef")
                        .HasColumnType("int")
                        .HasColumnName("PHASEREF");

                    b.Property<string>("ProfitingOwner")
                        .HasMaxLength(31)
                        .HasColumnType("nvarchar(31)")
                        .HasColumnName("PROFITINGOWNER");

                    b.Property<int?>("ResidenceGroupRef")
                        .HasColumnType("int")
                        .HasColumnName("RESIDENCEGROUPREF");

                    b.Property<string>("ResidenceNo")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("RESIDENCENO");

                    b.Property<int?>("ResidenceTypeRef")
                        .HasColumnType("int")
                        .HasColumnName("RESIDENCETYPEREF");

                    b.Property<int?>("ShareNo")
                        .HasColumnType("int")
                        .HasColumnName("SHARENO");

                    b.Property<string>("SpeCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SPECODE");

                    b.Property<short?>("TaxPayer")
                        .HasColumnType("smallint")
                        .HasColumnName("TAXPAYER");

                    b.Property<double?>("TotalBrutCoefficientMetre")
                        .HasColumnType("float")
                        .HasColumnName("TOTALBRUTCOEFFICIENTMETRE");

                    b.Property<double?>("TotalFuelMetre")
                        .HasColumnType("float")
                        .HasColumnName("TOTALFUELMETRE");

                    b.Property<double?>("TotalNetMetre")
                        .HasColumnType("float")
                        .HasColumnName("TOTALNETMETRE");

                    b.Property<string>("WaterMeterNo")
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)")
                        .HasColumnName("WATERMETERNO");

                    b.HasKey("Id");

                    b.ToTable("LG_XT001_211");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Module", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Module");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Settings", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SettingType")
                        .HasColumnType("int");

                    b.Property<int>("SettingValueType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsComplated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TransactionTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.TransactionItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionItem");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.TransactionType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ColorClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TransactionType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Claims", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.Module", "Module")
                        .WithMany("Claims")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.ExtendedProperties", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.Module", "Module")
                        .WithMany("ExtendedProperties")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.ExtendedPropertyRecordValues", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.ExtendedProperties", "ExtendedProperty")
                        .WithMany("RecordValues")
                        .HasForeignKey("ExtendedPropertyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ExtendedProperty");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.ExtendedPropertyValues", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.ExtendedProperties", "ExtendedProperty")
                        .WithMany("Values")
                        .HasForeignKey("ExtendedPropertyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ExtendedProperty");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.GeneratedIds", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.Module", "Module")
                        .WithMany("GeneratedIds")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Transaction", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.TransactionType", "TransactionType")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Koala.Yedpa.Core.Models.AppUser", "AppUser")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AppUser");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.TransactionItem", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.Transaction", "Transaction")
                        .WithMany("TransactionItems")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Koala.Yedpa.Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.AppUser", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.ExtendedProperties", b =>
                {
                    b.Navigation("RecordValues");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Module", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("ExtendedProperties");

                    b.Navigation("GeneratedIds");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Transaction", b =>
                {
                    b.Navigation("TransactionItems");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.TransactionType", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
