// <auto-generated />
using System;
using Koala.Yedpa.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Koala.Yedpa.Repositories.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811084906_AddSuperAdminRole")]
    partial class AddSuperAdminRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Koala.Yedpa.Core.Models.AppRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("StatusEnum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.BudgetRatio", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BuggetRatioMounths")
                        .HasColumnType("int");

                    b.Property<int>("BuggetType")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Ratio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalBugget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuggetType");

                    b.HasIndex("Year");

                    b.HasIndex("Code", "Year")
                        .IsUnique();

                    b.ToTable("BudgetRatio");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.BulkInvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("CanRetry")
                        .HasColumnType("bit");

                    b.Property<string>("ClientCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("LogoInvoiceRef")
                        .HasColumnType("int");

                    b.Property<string>("MonthName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrficheRef")
                        .HasColumnType("int");

                    b.Property<int>("Orflineref")
                        .HasColumnType("int");

                    b.Property<string>("RestError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("BulkInvoiceItems", "dbo");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.BulkInvoiceSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("InfoJobId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransferJobId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BulkInvoiceSessions", "dbo");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Claims", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Claims_Name_Unique");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.DashboardWidgetPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GridX")
                        .HasColumnType("int");

                    b.Property<int>("GridY")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.Property<string>("WidgetId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DashboardWidgetPreferences");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.DuesStatistic", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("April")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("August")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BudgetType")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<string>("BuggetRatioId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ClientRef")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("December")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DivCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DivName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("DocTrackingNr")
                        .HasColumnType("bigint");

                    b.Property<decimal>("February")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("January")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("July")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("June")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("March")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("May")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("November")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("October")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("September")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransferStatus")
                        .HasColumnType("int");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("DuesStatistics", "dbo");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.EmailTemplate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplate");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.ExtendedProperties", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InputType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShowOn")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("ExtendedProperties");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.ExtendedPropertyRecordValues", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExtendedPropertyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RecordId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExtendedPropertyId");

                    b.ToTable("ExtendedPropertyRecordValues");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.ExtendedPropertyValues", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtendedPropertyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExtendedPropertyId");

                    b.ToTable("ExtendedPropertyValues");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.GeneratedIds", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Digit")
                        .HasColumnType("int");

                    b.Property<int>("LastNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartNumber")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("GeneratedIds");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Module", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Module");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.QRCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FolderPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnerNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("QRCodeNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("QRImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("QrCodeYear")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("IX_QRCodes_BatchId");

                    b.HasIndex("PartnerNo")
                        .HasDatabaseName("IX_QRCodes_PartnerNo");

                    b.HasIndex("QRCodeNumber")
                        .HasDatabaseName("IX_QRCodes_QRCodeNumber");

                    b.HasIndex("QrCodeYear")
                        .HasDatabaseName("IX_QRCodes_QrCodeYear");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_QRCodes_Status");

                    b.HasIndex("PartnerNo", "QrCodeYear")
                        .IsUnique()
                        .HasDatabaseName("UQ_QRCodes_PartnerNo_Year");

                    b.ToTable("QRCodes", (string)null);
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.QRCodeBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QRCodeCount")
                        .HasColumnType("int");

                    b.Property<string>("QrCodePreCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("QrCodeYear")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SqlQuery")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CreateTime")
                        .HasDatabaseName("IX_QRCodeBatches_CreateTime");

                    b.HasIndex("QrCodeYear")
                        .HasDatabaseName("IX_QRCodeBatches_QrCodeYear");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_QRCodeBatches_Status");

                    b.ToTable("QRCodeBatches", (string)null);
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Settings", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SettingType")
                        .HasColumnType("int");

                    b.Property<int>("SettingValueType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsComplated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TransactionTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.TransactionItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionItem");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.TransactionType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ColorClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TransactionType");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Workplace", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasDefaultValueSql("(NEWID())");

                    b.Property<DateTime?>("ActiveResDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BegDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BlockRef")
                        .HasColumnType("int");

                    b.Property<double?>("BudgetDepotCoefficient1")
                        .HasColumnType("float");

                    b.Property<double?>("BudgetDepotCoefficient2")
                        .HasColumnType("float");

                    b.Property<double?>("BudgetDepotMetre1")
                        .HasColumnType("float");

                    b.Property<double?>("BudgetDepotMetre2")
                        .HasColumnType("float");

                    b.Property<double?>("BudgetFloorCoefficient")
                        .HasColumnType("float");

                    b.Property<double?>("BudgetFloorMetre")
                        .HasColumnType("float");

                    b.Property<double?>("BudgetGroundCoefficient")
                        .HasColumnType("float");

                    b.Property<double?>("BudgetGroundMetre")
                        .HasColumnType("float");

                    b.Property<double?>("BudgetHungCoefficient")
                        .HasColumnType("float");

                    b.Property<double?>("BudgetHungMetre")
                        .HasColumnType("float");

                    b.Property<double?>("BudgetPassageCoefficient1")
                        .HasColumnType("float");

                    b.Property<double?>("BudgetPassageCoefficient2")
                        .HasColumnType("float");

                    b.Property<double?>("BudgetPassageMetre1")
                        .HasColumnType("float");

                    b.Property<double?>("BudgetPassageMetre2")
                        .HasColumnType("float");

                    b.Property<string>("CalMeterNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CauldronRef")
                        .HasColumnType("int");

                    b.Property<short?>("ChiefReg")
                        .HasColumnType("smallint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short?>("CustomerType")
                        .HasColumnType("smallint");

                    b.Property<short?>("DeedInfo")
                        .HasColumnType("smallint");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("DimField")
                        .HasColumnType("float");

                    b.Property<double?>("DimGross")
                        .HasColumnType("float");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("FuelDepotCoefficient1")
                        .HasColumnType("float");

                    b.Property<double?>("FuelDepotCoefficient2")
                        .HasColumnType("float");

                    b.Property<double?>("FuelDepotMetre1")
                        .HasColumnType("float");

                    b.Property<double?>("FuelDepotMetre2")
                        .HasColumnType("float");

                    b.Property<double?>("FuelFloorCoefficient")
                        .HasColumnType("float");

                    b.Property<double?>("FuelFloorMetre")
                        .HasColumnType("float");

                    b.Property<double?>("FuelGroundCoefficient")
                        .HasColumnType("float");

                    b.Property<double?>("FuelGroundMetre")
                        .HasColumnType("float");

                    b.Property<double?>("FuelHungCoefficient")
                        .HasColumnType("float");

                    b.Property<double?>("FuelHungMetre")
                        .HasColumnType("float");

                    b.Property<double?>("FuelPassageCoefficient1")
                        .HasColumnType("float");

                    b.Property<double?>("FuelPassageCoefficient2")
                        .HasColumnType("float");

                    b.Property<double?>("FuelPassageMetre1")
                        .HasColumnType("float");

                    b.Property<double?>("FuelPassageMetre2")
                        .HasColumnType("float");

                    b.Property<double?>("GasCoefficient")
                        .HasColumnType("float");

                    b.Property<string>("HotWaterMeterNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdentityNr")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IndDivNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LogRef")
                        .HasColumnType("int");

                    b.Property<int>("LogicalRef")
                        .HasColumnType("int");

                    b.Property<int?>("ParcelRef")
                        .HasColumnType("int");

                    b.Property<short?>("PersonCount")
                        .HasColumnType("smallint");

                    b.Property<int?>("PhaseRef")
                        .HasColumnType("int");

                    b.Property<string>("ProfitingOwner")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("QRCodeGeneratedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("QRCodeImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("QRCodeNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ResidenceGroupRef")
                        .HasColumnType("int");

                    b.Property<string>("ResidenceNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ResidenceTypeRef")
                        .HasColumnType("int");

                    b.Property<int?>("ShareNo")
                        .HasColumnType("int");

                    b.Property<short?>("TaxPayer")
                        .HasColumnType("smallint");

                    b.Property<double?>("TotalBrutCoefficientMetre")
                        .HasColumnType("float");

                    b.Property<double?>("TotalFuelMetre")
                        .HasColumnType("float");

                    b.Property<double?>("TotalNetMetre")
                        .HasColumnType("float");

                    b.Property<string>("WaterMeterNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .HasDatabaseName("IX_Workplace_Code");

                    b.HasIndex("LogRef")
                        .IsUnique()
                        .HasDatabaseName("IX_Workplace_LogRef");

                    b.HasIndex("LogicalRef")
                        .IsUnique()
                        .HasDatabaseName("IX_Workplace_LogicalRef");

                    b.ToTable("Workplace", (string)null);
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Yonetim.Ariza", b =>
                {
                    b.Property<int>("ArizaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ARIZAID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArizaID"));

                    b.Property<string>("Birim")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("BIRIM");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Durum")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DURUM");

                    b.Property<string>("FirmaAdres")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("FIRMA-ADRES");

                    b.Property<bool>("Gizli")
                        .HasColumnType("bit")
                        .HasColumnName("GIZLI");

                    b.Property<string>("Konu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("KONU");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SonKisi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SONKISI");

                    b.Property<DateTime?>("SonTarih")
                        .HasColumnType("date")
                        .HasColumnName("SONTARIH");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime")
                        .HasColumnName("TARIH");

                    b.HasKey("ArizaID");

                    b.ToTable("ARIZA", "dbo");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Yonetim.ArizaHareket", b =>
                {
                    b.Property<int>("HareketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HAREKETID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HareketID"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ACIKLAMA");

                    b.Property<int>("ArizaID")
                        .HasColumnType("int")
                        .HasColumnName("ARIZAID");

                    b.Property<string>("Kisi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("KISI");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime")
                        .HasColumnName("TARIH");

                    b.HasKey("HareketID");

                    b.HasIndex("ArizaID");

                    b.ToTable("ARIZAHAREKET", "dbo");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Yonetim.ArizaKisi", b =>
                {
                    b.Property<int>("ArizaKisiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ARIZAKISIID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArizaKisiID"));

                    b.Property<int>("ArizaID")
                        .HasColumnType("int")
                        .HasColumnName("ARIZAID");

                    b.Property<int>("MailID")
                        .HasColumnType("int")
                        .HasColumnName("MAILID");

                    b.HasKey("ArizaKisiID");

                    b.HasIndex("ArizaID");

                    b.HasIndex("MailID");

                    b.ToTable("arizakisi", "dbo");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Yonetim.Birim", b =>
                {
                    b.Property<int>("BirimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BIRIMID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BirimID"));

                    b.Property<string>("BirimAdi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("BIRIMADI");

                    b.HasKey("BirimID");

                    b.ToTable("BIRIM", "dbo");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Yonetim.Bolme", b =>
                {
                    b.Property<int>("BolmeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BOLMEID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BolmeID"));

                    b.Property<string>("BolmeNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BOLMENO");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RafID")
                        .HasColumnType("int")
                        .HasColumnName("RAFID");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("BolmeID");

                    b.HasIndex("RafID");

                    b.ToTable("BOLME", "dbo");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Yonetim.Durum", b =>
                {
                    b.Property<int>("DurumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DURUMID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DurumID"));

                    b.Property<string>("DurumAdi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DURUMADI");

                    b.HasKey("DurumID");

                    b.ToTable("DURUM", "dbo");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Yonetim.Koli", b =>
                {
                    b.Property<int>("KoliID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KOLIID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KoliID"));

                    b.Property<int>("BolmeID")
                        .HasColumnType("int")
                        .HasColumnName("BOLMEID");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detay")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("detay");

                    b.Property<string>("KoliNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("KOLINO");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("KoliID");

                    b.HasIndex("BolmeID");

                    b.ToTable("KOLI", "dbo");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Yonetim.Mail", b =>
                {
                    b.Property<int>("MailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mailid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MailID"));

                    b.Property<string>("Ad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ad");

                    b.Property<string>("EPosta")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("eposta");

                    b.Property<string>("GSM")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("gsm");

                    b.Property<string>("Soyad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("soyad");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefon");

                    b.HasKey("MailID");

                    b.ToTable("mail", "dbo");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Yonetim.OtoparkKayit", b =>
                {
                    b.Property<int>("KayitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KAYITID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KayitID"));

                    b.Property<string>("AboneAd")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ABONEAD");

                    b.Property<DateTime?>("CikisTarih")
                        .HasColumnType("datetime")
                        .HasColumnName("CIKISTARIH");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GirisTarih")
                        .HasColumnType("datetime")
                        .HasColumnName("GIRISTARIH");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plaka")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PLAKA");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TELEFON");

                    b.HasKey("KayitID");

                    b.ToTable("kayit", "dbo");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Yonetim.Raf", b =>
                {
                    b.Property<int>("RafID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RAFID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RafID"));

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RafKod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("RAFKOD");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RafID");

                    b.ToTable("RAF", "dbo");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Yonetim.Sozlesme", b =>
                {
                    b.Property<int>("SozlesmeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SOZLESMEID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SozlesmeID"));

                    b.Property<bool>("Arsiv")
                        .HasColumnType("bit")
                        .HasColumnName("ARSIV");

                    b.Property<bool>("AzKalda")
                        .HasColumnType("bit")
                        .HasColumnName("AZKALDA");

                    b.Property<DateTime>("Baslangic")
                        .HasColumnType("date")
                        .HasColumnName("BASLANGIC");

                    b.Property<string>("Birim")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("BIRIM");

                    b.Property<DateTime>("Bitis")
                        .HasColumnType("date")
                        .HasColumnName("BITIS");

                    b.Property<bool>("Bitti")
                        .HasColumnType("bit")
                        .HasColumnName("BITTI");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firma")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("FIRMA");

                    b.Property<bool>("Gizli")
                        .HasColumnType("bit")
                        .HasColumnName("GIZLI");

                    b.Property<string>("Konu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("KONU");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdateUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Pdf")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("PDF");

                    b.Property<string>("SonKisi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SONKISI");

                    b.Property<DateTime?>("SonTarih")
                        .HasColumnType("date")
                        .HasColumnName("SONTARIH");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tur")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TUR");

                    b.HasKey("SozlesmeID");

                    b.ToTable("SOZLESME", "dbo");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Yonetim.SozlesmeKisi", b =>
                {
                    b.Property<int>("SozlesmeKisiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SOZLESMEKISIID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SozlesmeKisiID"));

                    b.Property<int>("MailID")
                        .HasColumnType("int")
                        .HasColumnName("MAILID");

                    b.Property<int>("SozlesmeID")
                        .HasColumnType("int")
                        .HasColumnName("SOZLESMEID");

                    b.HasKey("SozlesmeKisiID");

                    b.HasIndex("MailID");

                    b.HasIndex("SozlesmeID");

                    b.ToTable("sozlesmekisi", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.BulkInvoiceItem", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.BulkInvoiceSession", "Session")
                        .WithMany("Items")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Claims", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.Module", "Module")
                        .WithMany("Claims")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.ExtendedProperties", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.Module", "Module")
                        .WithMany("ExtendedProperties")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.ExtendedPropertyRecordValues", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.ExtendedProperties", "ExtendedProperty")
                        .WithMany("RecordValues")
                        .HasForeignKey("ExtendedPropertyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ExtendedProperty");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.ExtendedPropertyValues", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.ExtendedProperties", "ExtendedProperty")
                        .WithMany("Values")
                        .HasForeignKey("ExtendedPropertyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ExtendedProperty");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.GeneratedIds", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.Module", "Module")
                        .WithMany("GeneratedIds")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.QRCode", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.QRCodeBatch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Transaction", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.TransactionType", "TransactionType")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Koala.Yedpa.Core.Models.AppUser", "AppUser")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AppUser");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.TransactionItem", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.Transaction", "Transaction")
                        .WithMany("TransactionItems")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Yonetim.ArizaHareket", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.Yonetim.Ariza", "Ariza")
                        .WithMany("Hareketler")
                        .HasForeignKey("ArizaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ariza");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Yonetim.ArizaKisi", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.Yonetim.Ariza", "Ariza")
                        .WithMany("IlgiliKisiler")
                        .HasForeignKey("ArizaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Koala.Yedpa.Core.Models.Yonetim.Mail", "Mail")
                        .WithMany()
                        .HasForeignKey("MailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ariza");

                    b.Navigation("Mail");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Yonetim.Bolme", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.Yonetim.Raf", "Raf")
                        .WithMany("Bolumeler")
                        .HasForeignKey("RafID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Raf");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Yonetim.Koli", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.Yonetim.Bolme", "Bolme")
                        .WithMany("Koliler")
                        .HasForeignKey("BolmeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolme");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Yonetim.SozlesmeKisi", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.Yonetim.Mail", "Mail")
                        .WithMany()
                        .HasForeignKey("MailID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Koala.Yedpa.Core.Models.Yonetim.Sozlesme", "Sozlesme")
                        .WithMany("IlgiliKisiler")
                        .HasForeignKey("SozlesmeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mail");

                    b.Navigation("Sozlesme");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Koala.Yedpa.Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Koala.Yedpa.Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.AppUser", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.BulkInvoiceSession", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.ExtendedProperties", b =>
                {
                    b.Navigation("RecordValues");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Module", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("ExtendedProperties");

                    b.Navigation("GeneratedIds");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Transaction", b =>
                {
                    b.Navigation("TransactionItems");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.TransactionType", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Yonetim.Ariza", b =>
                {
                    b.Navigation("Hareketler");

                    b.Navigation("IlgiliKisiler");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Yonetim.Bolme", b =>
                {
                    b.Navigation("Koliler");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Yonetim.Raf", b =>
                {
                    b.Navigation("Bolumeler");
                });

            modelBuilder.Entity("Koala.Yedpa.Core.Models.Yonetim.Sozlesme", b =>
                {
                    b.Navigation("IlgiliKisiler");
                });
#pragma warning restore 612, 618
        }
    }
}
